a = int(input("请输入第一个数："))
b = int(input("请输入第二个数："))
jia = a + b
jian = a - b
cheng = a * b
chu = a / b
print("%s + %s = %s"%(a,b,jia))
print("%s - %s = %s"%(a,b,jian))
print("%s * %s = %s"%(a,b,cheng))
print("%s / %s = %s"%(a,b,chu))